# Copyright 2019-2025 The NATS Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

module NATS
  module Message
    # SUB initiates a subscription to a subject, optionally joining a distributed queue group.
    #
    # SEE: https://docs.nats.io/reference/reference-protocols/nats-protocol#sub
    struct SUB
      # The subject name to subscribe to.
      property subject : String
      # If specified, the subscriber will join this queue group.
      property queue_group : String? = nil
      # A unique alphanumeric subscription ID, generated by the client.
      property sid : String

      def initialize(
        @subject : String,
        @sid : String,
        @queue_group : String? = nil,
      )
      end

      def to_s
        if queue_group.nil?
          "SUB #{subject} #{sid}"
        else
          "SUB #{subject} #{queue_group} #{sid}"
        end
      end
    end
  end
end
